#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Compiles the Rust server for this project.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    parent_dir=$(pwd)
    cd "${parent_dir}/server"

    echo "==Waiting for PostgreSQL..."
    sleep 5.0
    while ! nc -z 0.0.0.0 5432; do
        sleep 5.0
    done

    echo "PostgreSQL started!"
    echo ""

    echo "==Compiling server..."
    cargo build

    cd "${parent_dir}"

    echo "Done!"
    echo ""
fi
