#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") [--clean]
Builds and runs the containerized database for this project.

--clean: Remove all images, containers and volumes.
"
}

# Parse args
while [[ "$#" > 0 ]]; do case $1 in
    --clean) CLEAN=1; shift;;
    --help) usage; exit 0; shift;;
    *) usage "Unknown parameter passed: $1"; shift; shift;;
esac; done

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    if [ "${CLEAN}" ]; then
        echo "==Pruning images and containers..."
        docker system prune -af

        echo "==Pruning volumes..."
        docker volume prune -f
    fi

    echo "==Building image..."
    docker-compose \
        -f docker-compose.yml build

    echo "==Starting database container..."
    docker-compose up -d

    echo "Running!"
    echo ""
fi
